name: Sync LeetCode Solutions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Daily at 12 PM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync LeetCode solutions
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: "leetcode-solutions/"  # Changed folder name
          filter-duplicate-secs: 86400  # Prevents duplicate syncs
